site_name: Nim 學習筆記
site_url: https://mydomain.org/
theme:
  name: material
  palette:
    scheme: slate
    primary: lime  # 主色調
    accent: red    # 強調色
  font:
    text: Roboto     
    code: Roboto Mono
  features:
    - content.code.copy
    - search.suggest
    - palette.toggle
    - navigation.tabs
    - navigation.tabs.sticky

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences

nav:
  - 入門與基礎: 
    - basic/01-start.md
    - basic/02-control-flow.md
    - basic/03-function-and-module.md
  - 資料結構與型別:
    - basic/04-data-type.md
    - basic/05-ref-and-pointer.md
    - basic/06-advanced-control.md
  - 進階主題:
    - basic/07-function-and-iterator.md
    - basic/08-types-in-detail.md
    - basic/09-modules-and-practice.md
  - 進階特性:
    - advanced/01-concept.md
    - advanced/02-oop.md
    - advanced/03-error-and-generic.md
    - advanced/04-template.md
    - advanced/05-pragmas.md
    - advanced/06-macros.md
  - 練習題:
    - practices/01-comment-and-declare.md
    - practices/02-type-inference-and-output.md
    - practices/03-condition-flow.md
    - practices/04-function-and-iterator.md
    - practices/05-types-in-detail.md
    - practices/06-modules-and-practice.md
    - practices/07-error-and-generic.md
    - practices/08-template.md
    - practices/09-pragmas.md
    - practices/10-macros.md
  - 30天挑戰:
    - challenges/README.md
    - challenges/day01.md
    - challenges/day02.md
    - challenges/day03.md
    - challenges/day04.md
    - challenges/day05.md
    - challenges/day06.md
    - challenges/day07.md
    - challenges/day08.md
    - challenges/day09.md
    - challenges/day10.md
    - challenges/day11.md
    - challenges/day12.md
    - challenges/day13.md
    - challenges/day14.md
    - challenges/day15.md
    - challenges/day16.md
    - challenges/day17.md
    - challenges/day18.md
    - challenges/day19.md
    - challenges/day20.md
    - challenges/day21.md
    - challenges/day22.md
    - challenges/day23.md
    - challenges/day24.md
    - challenges/day25.md
    - challenges/day26.md
    - challenges/day27.md
    - challenges/day28.md
    - challenges/day29.md
    - challenges/day30.md