site_name: nim 學習筆記
site_url: https://mydomain.org/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences

nav:
  - 基礎語法: 
    - basic/01-start.md
    - basic/02-control-flow.md
    - basic/03-function-and-module.md
    - basic/04-data-type.md
    - basic/05-ref-and-pointer.md
    - basic/06-advanced-control.md
    - basic/07-function-and-iterator.md
    - basic/08-types-in-detail.md
    - basic/09-modules-and-practice.md
  - 進階特性:
    - advanced/01-concept.md
    - advanced/02-oop.md
    - advanced/03-error-and-generic.md
    - advanced/04-template.md
    - advanced/05-pragmas.md
    - advanced/06-macros.md
  - 練習題:
    - practices/01-comment-and-declare.md
    - practices/02-type-inference-and-output.md
    - practices/03-condition-flow.md
    - practices/04-function-and-iterator.md
    - practices/05-types-in-detail.md
    - practices/06-modules-and-practice.md
    - practices/07-error-and-generic.md
    - practices/08-template.md
    - practices/09-macros.md
    - practices/10-pragmas.md